#!/bin/bash

! type -p wget >/dev/null && echo "wget not found" && exit

! type -p java >/dev/null && echo "java not found" && exit

! type -p jq >/dev/null && echo "jq not found" && exit

[[ ! -f downloadServer ]] && wget -q -c --content-disposition -P . -N "$REPO/$MASTER/server/downloadServer"
chmod +x ./downloadServer
./downloadServer "$SERVER"