#!/bin/bash

set -a

REPO="https://raw.githubusercontent.com/monull/minecraft-server-launcher"

BRANCH="master"

SERVER="paper-1.19.2-latest"

DIR=".server"

set +a

mkdir -p "$DIR" && cd "$DIR" || exit

[[ -f ../serverSetup ]] && cp ../serverSetup .
[[ ! -f serverSetup ]] && wget -q -c --content-disposition -P . -N "$REPO/$BRANCH/server/serverSetup" > /dev/null

chmod +x ./serverSetup
./serverSetup