#!/bin/bash

set -a

REPO="https://raw.githubusercontent.com/zeqky/minecraft-server-launcher"

BRANCH="master"

SERVER="paper-1.19.2-latest"

DIR=".server"

MEMORY=4

PLUGINS=(
  "one"
  "two"
)

PLAYERS=100

WORLDSF="worlds"

PLUGINSF="plugins"

PORT=-1

DEBUG_PORT=-1

set +a

mkdir -p "$DIR" && cd "$DIR" || exit

[[ -f ../downloadPlugins ]] && cp ../downloadPlugins .
[[ ! -f downloadPlugins ]] && wget -q -c --content-disposition -P . -N "$REPO/$BRANCH/server/startSetup" > /dev/null

chmod +x ./downloadPlugins
./downloadPlugins "${PLUGINS[@]}"