#!/bin/bash

set -a

REPO="https://raw.githubusercontent.com/zeqky/minecraft-server-launcher"

BRANCH="master"

SERVER="paper-1.19.2-latest"

DIR=".server"

MEMORY=4

PLUGINS=(
  'https://github.com/monun/auto-reloader/releases/download/0.0.5/auto-reloader-0.0.5.jar'
)

PLAYERS=100

WORLDSF="worlds"

PLUGINSF="plugins"

PORT=-1

DEBUG_PORT=-1

set +a

mkdir -p "$DIR" && cd "$DIR" || exit

[[ -f ../downloadPlugins ]] && cp ../downloadPlugins .
[[ ! -f downloadPlugins ]] && wget -q -c --content-disposition -P . -N "$REPO/$BRANCH/server/downloadPlugins" > /dev/null

chmod +x ./downloadPlugins
./downloadPlugins "${PLUGINS[@]}"